### ISSUE TITLE
Search Box for ressource return always "no result"

### ISSUE THREAD

**Issue by fredmasson** [OpenNMS/grafana-opennms-datasource#8] opened 2016-12-22 08:47 UTC
Hi,
I use Grafana 4.0.2 and Datasource Opennms 2.0.2 .
When i add a metric , the search node box show well Node filter result , but after if i search a ressource , the box show always "no result".
If i put the ressource name in entryFiel , i can search the attribute field.

it's a bug or a installation problem ?

thks.

**Comment by mukundparmar** [comment] 2016-12-22 18:38
I am having same problem today, everything running good upto Node Tree but when I click on ResourceID  shows "no result".

Thanks

**Comment by pbrane** [comment] 2016-12-22 19:47
> On Dec 22, 2016, at 3:47 AM, fredmasson <notifications@github.com> wrote:
> 
> it's a bug or a installation problem ?

The Plugin doesn’t support Grafana 4.  Go back to version 3.


David Hustace
The OpenNMS Group, Inc.

**Comment by pbrane** [comment] 2016-12-22 19:48
> On Dec 22, 2016, at 1:38 PM, mukundparmar <notifications@github.com> wrote:
> 
> I am having same problem today, everything running good upto Node Tree but when I click on ResourceID shows "no result”.

Go back to version Grafana version 3.  The plugin doesn’t support version 4.



David Hustace
The OpenNMS Group, Inc.

**Comment by fredmasson** [comment] 2016-12-22 19:58
i confirm , grafana 3.1.1 works fine with OpenNms 2.0.2

The Grafana fix for ELK 5.x is shortly with 4.1.x . When OpenNms plugin for Grafana 4 ?

thks.

**Comment by mukundparmar** [comment] 2016-12-22 20:35
Thank you I will try and let you know

On Dec 22, 2016 3:47 PM, "David Hustace" <notifications@github.com> wrote:


> On Dec 22, 2016, at 3:47 AM, fredmasson <notifications@github.com> wrote:
>
> it's a bug or a installation problem ?

The Plugin doesn’t support Grafana 4. Go back to version 3.


David Hustace
The OpenNMS Group, Inc.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenNMS/grafana-opennms-datasource/issues/8#issuecomment-268876154>,
or mute the thread

**Comment by pbrane** [comment] 2016-12-22 20:53
> On Dec 22, 2016, at 2:58 PM, fredmasson <notifications@github.com> wrote:
> 
> The Grafana fix for ELK 5.x is shortly with 4.1.x . When OpenNms plugin for Grafana 4 ?

Not sure.  It will happen, it’s just not on the radar until H19 is released and we’re thinking that will happen in mid to late January.

Which reminds me, the more of us that can help with the testing of the release branch, the quicker we can get it out and we can move on to other fun things, such as, updating the Grafana plugin.


For you RHEL 7/CentOS users:

# rpm -Uvh http://yum.opennms.org/repofiles/opennms-repo-branches-release-19.0.0-rhel7.noarch.rpm
# yum <update | install> opennms


Fedora Core 24:

# rpm -Uvh http://yum.opennms.org/repofiles/opennms-repo-branches-release-19.0.0-fc24.noarch.rpm
# yum <update | install> opennms


Debian/Ubuntu:

Create file: /etc/apt/sources.list.d/opennms.list
Containing:
deb http://debian.opennms.org branches/release-19.0.0 main
deb-src http://debian.opennms.org branches/release-19.0.0 main

# apt-get update 
# apt-get install -y opennms



Happy Holidays,
David Hustace
The OpenNMS Group, Inc.

**Comment by mukundparmar** [comment] 2016-12-22 22:19
IT worked.. thank you...

**Comment by j-white** [comment] 2017-01-04 15:51
Closing as duplicate of https://github.com/OpenNMS/grafana-opennms-datasource/issues/7

**Closed by j-white** 2017-01-04 15:51 UTC
